[program:testioc]
command=/bin/bash -c "cd /home/testioc && export HOME=/home/testioc && source /home/testioc/.testioc_bashrc && exec /opt/epics/pvxs/bin/$(/opt/epics/epics-base/startup/EpicsHostArch)/softIocPVX -v -m user=test -d /opt/epics/pvxs/test/testioc.db -d /opt/epics/pvxs/test/testiocg.db -a /home/testioc/testioc.acf"
environment=HOME="/home/testioc",USER="testioc"
user=testioc
autostart=true
autorestart=true

; Send logs to container stdout/stderr
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
