[program:pvacms]
environment=KRB5_KTNAME="/home/idm/.config/krb5/pvacms.keytab",KRB5_CLIENT_KTNAME="/home/idm/.config/krb5/pvacms.keytab",EPICS_AUTH_KRB_REALM="EPICS.ORG"
command=/bin/sh -c 'exec /opt/epics/pvxs-cms/bin/$(/opt/epics/epics-base/startup/EpicsHostArch)/pvacms --cluster-mode --cluster-discovery-timeout 30 --cluster-bidi-timeout 30 --cluster-skip-peer-identity-check --cert-auth-keychain /etc/pvacms/cert_auth.p12 --acf /etc/pvacms/pvacms.acf -v'
user=idm
autostart=true
autorestart=true
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
