# This is a Makefile fragment included by TOP/src/Makefile.

include $(AUTHN)/std/Makefile
#
#
##--------------------------------------------
##  ADD AUTHENTICATOR PLUGINS AFTER THIS LINE
#
#ifeq ($(PVXS_ENABLE_KRB_AUTH),YES)
#include $(AUTHN)/krb/Makefile
#endif
#
#ifeq ($(PVXS_ENABLE_LDAP_AUTH),YES)
#include $(AUTHN)/ldap/Makefile
#endif
