[program:krb5-kdc]
command=/usr/sbin/krb5kdc -n
autostart=true
autorestart=true

; Send logs to container stdout/stderr
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
