SRC_DIRS += $(PVACMS)
SRC_DIRS += $(AUTHN)

USR_CPPFLAGS += -I$(PVACMS)
USR_CPPFLAGS += -I$(AUTHN)
USR_CPPFLAGS += -I$(AUTHN_STD)

# PVACMS sources
PROD += pvacms
pvacms_SRCS += pvacms.cpp
pvacms_SRCS += configcms.cpp


