dockerRegistry: "ghcr.io"
dockerUsername: "slac-epics"

images:
  idm:
    name: "idm"
    tag: "dev"
  internet:
    name: "internet"
    tag: "dev"
  it:
    name: "idm"
    tag: "dev"
  testioc:
    name: "testioc"
    tag: "dev"
  tstioc:
    name: "tstioc"
    tag: "dev"
  ml:
    name: "ml"
    tag: "dev"
  mlIoc:
    name: "ml-ioc"
    tag: "dev"
  gateway:
    name: "gateway"
    tag: "dev"
  lab:
    name: "lab"
    tag: "dev"
  csStudio:
    name: "cs-studio"
    tag: "dev"

imagePullPolicy: IfNotPresent

idm:
  replicas: 1
  service:
    name: "idm"
    udpPort: 88
    tcpPort: 749
    pwdPort: 464

  expose:
    nodePortUdp: 30088
    nodePortTcp: 30049

  debug:
    enabled: false
    logLevel: "pvxs.*=INFO"
  persistence:
    enabled: true
    size: 64Mi
    dataSize: 256Mi
    storageClassName: ""

internet:
  replicas: 1
  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

it:
  replicas: 1
  debug:
    enabled: false
    logLevel: "pvxs.*=INFO"
  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

ml:
  replicas: 1
  debug:
    enabled: false
    logLevel: "pvxs.*=INFO"
  persistence:
    enabled: true
    size: 64Mi
    dataSize: 256Mi
    storageClassName: ""

mlIoc:
  replicas: 1
  debug:
    enabled: false
    logLevel: "pvxs.*=INFO"
  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

mlGateway:
  replicas: 1
  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

  config: |
    {
      "version": 2,
      "readOnly": false,
      "clients": [
        {
          "name": "ml-local",
          "autoaddrlist": false,
          "addrlist": "{{ include "pvxs-lab.mlService" . }} {{ include "pvxs-lab.mlIocService" . }}",
          "tls_keychain": "/home/gateway/.config/pva/1.5/gateway.p12"
        }
      ],
      "servers": [
        {
          "name": "internet",
          "clients": ["ml-local"],
          "acf_client": "ml-local",
          "statusprefix": "GW:STS:",
          "autoaddrlist": false,
          "addrlist": "{{ include "pvxs-lab.mlService" . }}",
          "tls_keychain": "/home/gateway/.config/pva/1.5/gateway.p12",
          "serverport": "5075",
          "EPICS_PVAS_TLS_PORT": "5076",
          "bcastport": "5076",
          "access": "gateway.acf",
          "pvlist": "internet.pvlist"
        },
        {
          "name": "cross-zone",
          "clients": ["ml-local"],
          "statusprefix": "GW:STS:",
          "autoaddrlist": false,
          "addrlist": "{{ include "pvxs-lab.mlService" . }}",
          "tls_keychain": "/home/gateway/.config/pva/1.5/gateway.p12",
          "serverport": "5175",
          "EPICS_PVAS_TLS_PORT": "5176",
          "bcastport": "5176",
          "access": "gateway.acf",
          "pvlist": "cross-zone.pvlist"
        },
        {
          "name": "downstream_status",
          "clients": [],
          "interface": ["127.0.0.1"],
          "serverport": "0",
          "statusprefix": "GW:STS:"
        }
      ]
    }

  internetPvlist: |
    ml:.* ALLOW

  crossZonePvlist: |
    CERT:CLUSTER(?::.*)? ALLOW CERT_CLUSTER

testioc:
  replicas: 1
  debug:
    enabled: false
    logLevel: "pvxs.*=INFO"
  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

tstioc:
  replicas: 1
  debug:
    enabled: false
    logLevel: "pvxs.*=INFO"
  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

gateway:
  replicas: 1
  hostNetwork: false    # for NodePort mode
  # externalInterface: 123.45.6.7   # egress if defined
  separate_server_keychain: false

  expose: {}

  config: |
    {
      "version": 2,
      "readOnly": false,
      "clients": [
        {
          "name": "local",
          "autoaddrlist": false,
          "addrlist": "{{ include "pvxs-lab.pvacmsService" . }} {{ include "pvxs-lab.testiocService" . }} {{ include "pvxs-lab.tstiocService" . }}",
          "tls_keychain": "/home/gateway/.config/pva/1.5/gateway.p12"
        }
      ],
      "servers": [
        {
          "name": "ml",
          "clients": ["local"],
          "acf_client": "local",
          "statusprefix": "GW:STS:",
          "autoaddrlist": false,
          "addrlist": "{{ include "pvxs-lab.pvacmsService" . }}",
          "tls_keychain": "/home/gateway/.config/pva/1.5/gateway{{ if .Values.gateway.separate_server_keychain }}{{ "S" }}{{ end }}.p12",
          "serverport": "5075",
          "EPICS_PVAS_TLS_PORT": "5076",
          "bcastport": "5076",
          "access": "gateway.acf",
          "pvlist": "ml.pvlist"
        },
        {
          "name": "internet",
          "clients": ["local"],
          "acf_client": "local",
          "statusprefix": "GW:STS:",
          "autoaddrlist": false,
          "addrlist": "{{ include "pvxs-lab.pvacmsService" . }}",
          "tls_keychain": "/home/gateway/.config/pva/1.5/gateway{{ if .Values.gateway.separate_server_keychain }}{{ "S" }}{{ end }}.p12",
          "serverport": "5275",
          "EPICS_PVAS_TLS_PORT": "5276",
          "bcastport": "5276",
          "access": "gateway.acf",
          "pvlist": "internet.pvlist"
        },
        {
          "name": "cross-zone",
          "clients": ["local"],
          "statusprefix": "GW:STS:",
          "autoaddrlist": false,
          "addrlist": "{{ include "pvxs-lab.pvacmsService" . }}",
          "tls_keychain": "/home/gateway/.config/pva/1.5/gateway{{ if .Values.gateway.separate_server_keychain }}{{ "S" }}{{ end }}.p12",
          "serverport": "5175",
          "EPICS_PVAS_TLS_PORT": "5176",
          "bcastport": "5176",
          "access": "gateway.acf",
          "pvlist": "cross-zone.pvlist"
        },
        {
          "name": "downstream_status",
          "clients": [],
          "interface": ["127.0.0.1"],
          "serverport": "0",
          "statusprefix": "GW:STS:"
        }
      ]
    }

  internetPvlist: |
    test:.* ALLOW
    tst:.* ALLOW
    test:spec ALLOW SPECIAL
    CERT:CLUSTER(?::.*)? DENY
    CERT:CREATE(?::.*)? ALLOW CERT_CREATE
    CERT:STATUS(?::.*)? ALLOW CERT_STATUS
    CERT:HEALTH(?::.*)? ALLOW
    CERT:METRICS(?::.*)? ALLOW

  mlPvlist: |
    test:.* ALLOW
    tst:.* ALLOW
    test:spec ALLOW SPECIAL

  crossZonePvlist: |
    CERT:CLUSTER(?::.*)? ALLOW CERT_CLUSTER

  debug:
    enabled: false
    logLevel: "p4p.gw=DEBUG,pvxs.*=DEBUG"

  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

csStudioLab:
  replicas: 1
  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

csStudioMl:
  replicas: 1
  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

csStudioInternet:
  replicas: 1
  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

lab:
  image: "lab:dev"
  replicas: 1

  persistence:
    enabled: true
    size: 64Mi
    storageClassName: ""

  keepalive:
    enabled: true
    command: ["/bin/sh", "-lc"]
    args: ["sleep infinity"]

# Internal PVAccess ports (PVXS/P4P defaults)
ports:
  pvaTcp: 5075
  pvaUdp: 5076
  pvaTls: 5076
  exposePvaTls: true

