apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvxs-lab.certAdminLabService" . }}
  labels:
    {{- include "pvxs-lab.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: cert-admin-lab
    release: {{ .Release.Name }}
  ports:
    - name: novnc
      port: 8080
      targetPort: 8080
      protocol: TCP
