apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvxs-lab.csStudioMlService" . }}
  labels:
    {{- include "pvxs-lab.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: cs-studio-ml
    release: {{ .Release.Name }}
  ports:
    - name: novnc
      port: 8080
      targetPort: 8080
      protocol: TCP
