apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-gateway
  labels:
    {{- include "pvxs-lab.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: gateway
    release: {{ .Release.Name }}
  ports:
    - name: pva-tcp
      protocol: TCP
      port: {{ .Values.ports.pvaTcp }}
      targetPort: pva-tcp
    - name: pva-tls
      protocol: TCP
      port: {{ .Values.ports.pvaTls }}
      targetPort: pva-tls
    - name: pva-udp
      protocol: UDP
      port: {{ .Values.ports.pvaUdp }}
      targetPort: pva-udp
    - name: inet-tcp
      protocol: TCP
      port: 5275
      targetPort: inet-tcp
    - name: inet-udp
      protocol: UDP
      port: 5276
      targetPort: inet-udp
    - name: inet-tls
      protocol: TCP
      port: 5276
      targetPort: inet-tls

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvxs-lab.gatewayService" . }}-xgw
  labels:
    {{- include "pvxs-lab.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: gateway
    release: {{ .Release.Name }}
  ports:
    - name: xgw-tcp
      protocol: TCP
      port: 5175
      targetPort: xgw-tcp
    - name: xgw-udp
      protocol: UDP
      port: 5176
      targetPort: xgw-udp
    - name: xgw-tls
      protocol: TCP
      port: 5176
      targetPort: xgw-tls
