apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-idm
  labels:
    {{- include "pvxs-lab.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: idm
    release: {{ .Release.Name }}
  ports:
    - name: pva-tcp
      port: {{ .Values.ports.pvaTcp }}
      targetPort: pva-tcp
      protocol: TCP
    - name: pva-udp
      port: {{ .Values.ports.pvaUdp }}
      targetPort: pva-udp
      protocol: UDP
  {{- if .Values.idm.expose.nodePortUdp }}
    - name: kerberos
      port: {{ .Values.idm.service.udpPort }}
      targetPort: kerberos
      nodePort: {{ .Values.idm.expose.nodePortUdp }}
      protocol: UDP
  {{- end }}
  {{- if .Values.idm.expose.nodePortTcp }}
    - name: admin
      port: {{ .Values.idm.service.tcpPort }}
      targetPort: admin
      nodePort: {{ .Values.idm.expose.nodePortTcp }}
      protocol: TCP
  {{- end }}
