apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvxs-lab.mlGatewayService" . }}
  labels:
    {{- include "pvxs-lab.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: ml-gateway
    release: {{ .Release.Name }}
  ports:
    - name: pva-tcp
      protocol: TCP
      port: {{ .Values.ports.pvaTcp }}
      targetPort: pva-tcp
    - name: pva-tls
      protocol: TCP
      port: {{ .Values.ports.pvaTls }}
      targetPort: pva-tls
    - name: pva-udp
      protocol: UDP
      port: {{ .Values.ports.pvaUdp }}
      targetPort: pva-udp

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pvxs-lab.mlGatewayService" . }}-xgw
  labels:
    {{- include "pvxs-lab.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: ml-gateway
    release: {{ .Release.Name }}
  ports:
    - name: xgw-tcp
      protocol: TCP
      port: 5175
      targetPort: xgw-tcp
    - name: xgw-udp
      protocol: UDP
      port: 5176
      targetPort: xgw-udp
