apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pvxs-lab.mlGatewayService" . }}-conf
  labels:
    {{- include "pvxs-lab.labels" . | nindent 4 }}
data:
  gateway.conf: |-
  {{ tpl .Values.mlGateway.config . | nindent 4 }}
  internet.pvlist: |
  {{ .Values.mlGateway.internetPvlist | nindent 4 }}
  cross-zone.pvlist: |
  {{ .Values.mlGateway.crossZonePvlist | nindent 4 }}
