{{- $sc := "" -}}

{{- if .Values.testioc.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-testioc-pva
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.testioc.persistence.storageClassName }}
  storageClassName: {{ .Values.testioc.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.testioc.persistence.size | quote }}
---
{{- end }}

{{- if .Values.tstioc.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-tstioc-pva
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.tstioc.persistence.storageClassName }}
  storageClassName: {{ .Values.tstioc.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.tstioc.persistence.size | quote }}
---
{{- end }}

{{- if .Values.gateway.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-gateway-pva
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.gateway.persistence.storageClassName }}
  storageClassName: {{ .Values.gateway.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.gateway.persistence.size | quote }}
---
{{- end }}

{{- if .Values.lab.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-lab-pva
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.lab.persistence.storageClassName }}
  storageClassName: {{ .Values.lab.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.lab.persistence.size | quote }}
---
{{- end }}
  {{- if .Values.idm.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-idm-config
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.idm.persistence.storageClassName }}
  storageClassName: {{ .Values.idm.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.idm.persistence.size | quote }}
---
{{- end }}

{{- if .Values.idm.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-idm-data
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.idm.persistence.storageClassName }}
  storageClassName: {{ .Values.idm.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.idm.persistence.dataSize | default "256Mi" | quote }}
{{- end }}

---
{{- if .Values.internet.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-internet-pva
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.internet.persistence.storageClassName }}
  storageClassName: {{ .Values.internet.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.internet.persistence.size | quote }}
{{- end }}

---
{{- if .Values.it.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-it-config
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.it.persistence.storageClassName }}
  storageClassName: {{ .Values.it.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.it.persistence.size | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-it-data
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.it.persistence.storageClassName }}
  storageClassName: {{ .Values.it.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.it.persistence.size | quote }}
{{- end }}

---
{{- if .Values.ml.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-ml-config
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.ml.persistence.storageClassName }}
  storageClassName: {{ .Values.ml.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ml.persistence.size | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-ml-data
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.ml.persistence.storageClassName }}
  storageClassName: {{ .Values.ml.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.ml.persistence.dataSize | default "256Mi" | quote }}
{{- end }}

---
{{- if .Values.mlIoc.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-ml-ioc-pva
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.mlIoc.persistence.storageClassName }}
  storageClassName: {{ .Values.mlIoc.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mlIoc.persistence.size | quote }}
{{- end }}

---
{{- if .Values.mlGateway.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvxs-lab.fullname" . }}-ml-gateway-pva
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.mlGateway.persistence.storageClassName }}
  storageClassName: {{ .Values.mlGateway.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mlGateway.persistence.size | quote }}
{{- end }}
