[program:mlioc]
command=/bin/bash -c "cd /home/mlioc && export HOME=/home/mlioc && source /home/mlioc/.mlioc_bashrc && exec /opt/epics/pvxs/bin/$(/opt/epics/epics-base/startup/EpicsHostArch)/softIocPVX -v -m user=ml -d /home/mlioc/mlioc.db"
environment=HOME="/home/mlioc",USER="mlioc"
user=mlioc
autostart=true
autorestart=true
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
