[program:tstioc]
command=/bin/bash -c "cd /home/tstioc && export HOME=/home/tstioc && source /home/tstioc/.tstioc_bashrc && exec /opt/epics/pvxs/bin/$(/opt/epics/epics-base/startup/EpicsHostArch)/softIocPVX -v -m N=tst,P=tst -d /opt/epics/pvxs/test/image.db -G /opt/epics/pvxs/test/image.json -a /home/tstioc/tstioc.acf"
environment=HOME="/home/tstioc",USER="tstioc"
user=tstioc
autostart=true
autorestart=true

; Send logs to container stdout/stderr
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
stopsignal=TERM
stopasgroup=true
killasgroup=true
