[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1920x1080x24
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0

[program:fluxbox]
command=/usr/bin/fluxbox
environment=DISPLAY=":99"
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0

[program:x11vnc]
command=bash -c 'if [ -n "$VNC_PASSWORD" ]; then mkdir -p /tmp/.vnc && x11vnc -storepasswd "$VNC_PASSWORD" /tmp/.vnc/passwd && exec x11vnc -display :99 -forever -shared -rfbport 5900 -rfbauth /tmp/.vnc/passwd; else exec x11vnc -display :99 -forever -shared -rfbport 5900 -nopw; fi'
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0

[program:websockify]
command=/usr/bin/websockify --web /usr/share/novnc 8080 localhost:5900
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/proc/1/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/proc/1/fd/2
stderr_logfile_maxbytes=0
